### ISSUE TITLE
Codeanpassungen_Logic

### ISSUE THREAD

**Issue by JulianRetzbach** [luisafuss/muehle-studienarbeit#46]
Allgemein:
- Für jede Funktion sollten Sie sowohl Eingabe, Ausgabe, als auch Nebenefekte beschreiben. Bisher sind die Kommentare viel zu knapp.

Testboards:
- für Unit-Tests verwenden => und aus Logic entfernen
- Beschreiben welche Informationen hier beschrieben werden

Funktion get_player_phase(pieces, player):
- erklären, wie player kodiert wird

Funktion possible_positions_phase_two(pieces, player, ring, cell):
-So umbauen, dass neighboring nur Positionen aufsammelt, die leer sind

Funktion next_positions(pieces, player, ring, cell):
- ring und cell sind nicht ausreichen definiert

Funktion make_move(ring, cell):
- Die Funktion ist logisch zu Komplex und soll aufgespalten werden
- nicht mit globalen Variablen (status) arbeiten
"Die Funktion hat keine klare Aufgabe. Wenn Sie später eine KI-Engine entwickeln wollen, dann brauchen Sie eine Funktion next_states(State, player), die zu einem gegebenem Zustand State, bei der player am Zug ist, die Folgezustände berechnet, nicht irgendetwas dazwischen."

Funktion handle_mills(status):
-Einrückung in der oberen Schleife anpassen
-das x/i in der ersten Schleifen durch ring/cell austauschen
-x in der zweiten Schleife durch 0 ersetzen
=> Ich kann mich eigentlich daran erinnern das schon einmal erledigt zu haben.

**Comment by luisafuss** [comment]
Ausgelagertes Issue: #72
