### ISSUE TITLE
Make Move

### ISSUE THREAD

**Issue by JulianRetzbach** [luisafuss/muehle-studienarbeit#72]
Funktion make_move(ring, cell):
- Die Funktion ist logisch zu Komplex und soll aufgespalten werden
- nicht mit globalen Variablen (status) arbeiten
"Die Funktion hat keine klare Aufgabe. Wenn Sie später eine KI-Engine entwickeln wollen, dann brauchen Sie eine Funktion next_states(State, player), die zu einem gegebenem Zustand State, bei der player am Zug ist, die Folgezustände berechnet, nicht irgendetwas dazwischen."

**Comment by luisafuss** [comment]
Hängt mit #67 und #58  zusammen
